### ISSUE TITLE
图片加载不全，一部分一直保持模糊状态

### ISSUE THREAD

**Issue by GodStream** [ccforward/progressive-image#5]
我的vue项目遇到这样一个问题，同一个页面我用到两个v-progressive指令，分别有两个板块的图片，但是最多只能加载出一个屏幕区域的图片，其它图片就会一直保持模糊状态不在加载，请问这该怎么解决呢？

**Comment by ccforward** [comment]
有没有demo  我可以看下的？

**Comment by GodStream** [comment]
因为是公司项目，不太好拿出来也不方便。情况是这样的，一个页面分别有两组数据通过请求得到，进行v-for渲染出来，最终只能得到一个屏幕内的图片，其余图片都保持模糊状态，不管怎样滑动都不再变化。问题比较奇怪。
